languages=['English','French','Indonesian']
print(languages[1])
print(languages[2])
print(languages[-1])
message = "I can speak " + languages[0].title() + " fluently."
print(message)
languages[0]='Hindi'
print(languages)
languages.append('English')
print(languages)
languages.insert(0, 'Spanish')
print(languages)
del languages[1]
print(languages)
popped_languages = languages.pop(0)
print(languages)
print(popped_languages)
most_used = languages.pop()
print("I speak " + most_used.title() + " in my daily basis.")
languages.remove('French')
print(languages)
languages.append('Dutch')
languages.append('Arabic')
languages.append('Italian')
print(languages)
difficult = 'Dutch'
languages.remove(difficult)
print(languages)
print("\nThe most difficult language for me is  " + difficult.title() + " therefore I rarely use it.")
languages.sort()
print(languages)
languages.sort(reverse=True)
print(languages)
languages.reverse()
print(languages)
len(languages)
print(len(languages))
